# Generated by Django 5.2.8 on 2025-11-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0003_marvelcomic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarvelComic',
        ),
        migrations.AlterField(
            model_name='product_variety',
            name='image',
            field=models.ImageField(upload_to='product_categories/'),
        ),
    ]
