# Generated by Django 5.2.8 on 2025-11-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0004_delete_marvelcomic_alter_product_variety_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_variety',
            new_name='ProductVariety',
        ),
        migrations.AlterModelOptions(
            name='productvariety',
            options={'ordering': ['name'], 'verbose_name': 'Product Variety', 'verbose_name_plural': 'Product Varieties'},
        ),
    ]
